import http from 'http';
import fs from 'fs/promises';
import fsSync from 'fs';
import path from 'path';
import crypto from 'crypto';
import {fileURLToPath} from 'url';
import {URL} from 'url';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const PORT=Number(process.env.PORT||3000), HOST=process.env.HOST||'0.0.0.0';
const ADMIN_USERNAME=(process.env.ADMIN_EMAIL||process.env.ADMIN_USERNAME||'mrinal@biharithaath.com').trim().toLowerCase(), ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'mrinaldemo2026';
const SESSION_SECRET=process.env.SESSION_SECRET||'bihari-thaath-demo-session-secret-change-me';
const DATA_DIR=path.join(__dirname,'data'), DATA_FILE=path.join(DATA_DIR,'menu.json'), UPLOAD_DIR=path.join(__dirname,'public','uploads');
const MIME={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.avif':'image/avif','.svg':'image/svg+xml'};
const categories=['Recommended','Veg Starters','Non-Veg Starters','Kebabs','Indian Veg Main Course','Indian Non-Veg Main Course','Biryani & Rice','Dal','Roti / Naan / Paratha','Chinese / Oriental','Soups','Salad & Raita','Desserts / Mithai'];
const seedItems=[
{id:'bt-001',name:'Murgh Malai Tikka',category:'Kebabs',price:468,unit:'8 pcs',stockQty:12,description:'Creamy, tender chicken tikka with a gentle char and rich marinade.',image:'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=1200&q=85',featured:true,active:true},
{id:'bt-002',name:'Paneer Tikka',category:'Veg Starters',price:333,unit:'8 pcs',stockQty:14,description:'Char-grilled paneer with aromatic spices, peppers and a smoky finish.',image:'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=1200&q=85',featured:true,active:true},
{id:'bt-003',name:'Kadhai Murgh',category:'Indian Non-Veg Main Course',price:428,unit:'Half',stockQty:10,description:'Rustic chicken curry with peppers, tomato, ginger and fragrant spices.',image:'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=85',featured:true,active:true},
{id:'bt-004',name:'Subz Biryani',category:'Biryani & Rice',price:279,unit:'Serves 1',stockQty:9,description:'Fragrant basmati rice layered with vegetables and whole spices.',image:'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=1200&q=85',featured:false,active:true},
{id:'bt-005',name:'Butter Chicken',category:'Indian Non-Veg Main Course',price:441,unit:'Half',stockQty:8,description:'Tender chicken in a creamy tomato gravy with a balanced buttery finish.',image:'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=1200&q=85',featured:true,active:true},
{id:'bt-006',name:'Veg Kebab Platter',category:'Veg Starters',price:617,unit:'Platter',stockQty:6,description:'A generous vegetarian platter featuring assorted kebab favourites.',image:'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=1200&q=85',featured:false,active:true},
{id:'bt-007',name:'Tandoori Chicken',category:'Kebabs',price:387,unit:'Half',stockQty:0,description:'Classic tandoori chicken with a smoky roasted exterior and juicy centre.',image:'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=1200&q=85',featured:false,active:true},
{id:'bt-008',name:'Dal Makhani',category:'Dal',price:333,unit:'Full',stockQty:11,description:'Slow-cooked black lentils finished with butter and gentle smoky notes.',image:'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=1200&q=85',featured:false,active:true},
{id:'bt-009',name:'Lachha Paratha',category:'Roti / Naan / Paratha',price:77,unit:'2 pcs',stockQty:25,description:'Layered, flaky paratha made for curries, kebabs and hearty meals.',image:'https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&w=1200&q=85',featured:false,active:true},
{id:'bt-010',name:'Hot Gulab Jamun',category:'Desserts / Mithai',price:104,unit:'2 pcs',stockQty:16,description:'Warm gulab jamun served as a comforting sweet finish to the meal.',image:'https://images.unsplash.com/photo-1601303516534-1b4c7f0b2f72?auto=format&fit=crop&w=1200&q=85',featured:false,active:true}
];
async function ensure(){await fs.mkdir(DATA_DIR,{recursive:true});await fs.mkdir(UPLOAD_DIR,{recursive:true});try{await fs.access(DATA_FILE)}catch{await fs.writeFile(DATA_FILE,JSON.stringify(seedItems,null,2))}}
async function readItems(){return JSON.parse(await fs.readFile(DATA_FILE,'utf8'))}
async function writeItems(x){const t=DATA_FILE+'.tmp';await fs.writeFile(t,JSON.stringify(x,null,2));await fs.rename(t,DATA_FILE)}
const clean=(v,n=600)=>String(v??'').trim().slice(0,n);const bool=(v,d=false)=>v===undefined?d:(v===true||v==='true'||v==='1'||v==='on');
function pub(x){return {...x,stockQty:Number(x.stockQty)||0,inStock:(Number(x.stockQty)||0)>0}}
function token(){const p=Buffer.from(JSON.stringify({u:ADMIN_USERNAME,e:Date.now()+43200000})).toString('base64url');return p+'.'+crypto.createHmac('sha256',SESSION_SECRET).update(p).digest('base64url')}
function auth(req){const raw=req.headers.cookie||'';const m=raw.match(/(?:^|;\s*)bt_session=([^;]+)/);if(!m)return false;try{const [p,s]=decodeURIComponent(m[1]).split('.'),e=crypto.createHmac('sha256',SESSION_SECRET).update(p).digest('base64url');if(s.length!==e.length||!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(e)))return false;const d=JSON.parse(Buffer.from(p,'base64url').toString());return d.u===ADMIN_USERNAME&&d.e>Date.now()}catch{return false}}
function send(res,status,data,headers={}){const body=Buffer.from(JSON.stringify(data));res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers,'Content-Length':body.length});res.end(body)}
function redirect(res,loc){res.writeHead(302,{Location:loc});res.end()}
async function body(req){const chunks=[];for await(const c of req)chunks.push(c);return Buffer.concat(chunks)}
function parseUrlEncoded(buf){return Object.fromEntries(new URLSearchParams(buf.toString()))}
function parseMultipart(buf,contentType){const m=contentType.match(/boundary=(?:"([^"]+)"|([^;]+))/i);if(!m)throw new Error('Invalid multipart boundary');const boundary=Buffer.from('--'+(m[1]||m[2]));const out={fields:{},files:{}};let pos=0;while(true){const start=buf.indexOf(boundary,pos);if(start<0)break;let partStart=start+boundary.length;if(buf.slice(partStart,partStart+2).toString()==='--')break;if(buf.slice(partStart,partStart+2).toString()==='\r\n')partStart+=2;const next=buf.indexOf(boundary,partStart);if(next<0)break;const part=buf.slice(partStart,next-2);const split=part.indexOf(Buffer.from('\r\n\r\n'));if(split<0){pos=next;continue}const head=part.slice(0,split).toString();const data=part.slice(split+4);const nm=head.match(/name="([^"]+)"/i);if(!nm){pos=next;continue}const name=nm[1];const fn=head.match(/filename="([^"]*)"/i);if(fn&&fn[1]){const ct=(head.match(/content-type:\s*([^\r\n]+)/i)||[])[1]||'application/octet-stream';out.files[name]={filename:path.basename(fn[1]),mime:ct,data};}else out.fields[name]=data.toString();pos=next}return out}
async function formData(req){const b=await body(req),ct=req.headers['content-type']||'';if(ct.includes('multipart/form-data'))return parseMultipart(b,ct);return {fields:parseUrlEncoded(b),files:{}}}
function priceOk(v){return Number.isFinite(Number(v))&&Number(v)>=0}
async function saveUpload(file){if(!file)return null;if(!/^image\/(jpeg|png|webp|avif)$/.test(file.mime))throw new Error('Only JPG, PNG, WEBP or AVIF images are allowed.');if(file.data.length>4*1024*1024)throw new Error('Image must be 4MB or smaller.');const ext={ 'image/jpeg':'.jpg','image/png':'.png','image/webp':'.webp','image/avif':'.avif'}[file.mime]||'.img';const name=crypto.randomUUID()+ext;await fs.writeFile(path.join(UPLOAD_DIR,name),file.data);return '/uploads/'+name}
async function handleApi(req,res,u){
 const pathname=u.pathname;
 if(pathname==='/api/health'&&req.method==='GET')return send(res,200,{ok:true,service:'bihari-thaath-demo'});
 if(pathname==='/api/categories'&&req.method==='GET')return send(res,200,categories);
 if(pathname==='/api/menu'&&req.method==='GET'){try{let items=(await readItems()).filter(x=>x.active).map(pub);const q=clean(u.searchParams.get('q'),80).toLowerCase(),c=clean(u.searchParams.get('category'),80);if(q)items=items.filter(x=>[x.name,x.category,x.description].some(v=>v.toLowerCase().includes(q)));if(c&&c!=='Recommended')items=items.filter(x=>x.category===c);if(c==='Recommended')items=items.filter(x=>x.featured);return send(res,200,items)}catch(e){console.error(e);return send(res,500,{error:'Unable to load the menu right now.'})}}
 if(pathname.startsWith('/api/menu/')&&req.method==='GET'){try{const id=pathname.split('/').pop(),x=(await readItems()).find(x=>x.id===id&&x.active);return x?send(res,200,pub(x)):send(res,404,{error:'Dish not found.'})}catch{return send(res,500,{error:'Unable to load this dish.'})}}
 if(pathname==='/api/auth/login'&&req.method==='POST'){try{const b=parseUrlEncoded(await body(req));if(clean(b.username,80)!==ADMIN_USERNAME||String(b.password||'')!==ADMIN_PASSWORD)return send(res,401,{error:'Incorrect username or password.'});return send(res,200,{ok:true},{'Set-Cookie':`bt_session=${token()}; Path=/; HttpOnly; SameSite=Lax; Max-Age=43200`})}catch{return send(res,400,{error:'Invalid login request.'})}}
 if(pathname==='/api/auth/logout'&&req.method==='POST')return send(res,200,{ok:true},{'Set-Cookie':'bt_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0'});
 if(pathname==='/api/auth/me'&&req.method==='GET')return send(res,200,{authenticated:auth(req),username:ADMIN_USERNAME});
 if(pathname.startsWith('/api/admin/')){
   if(!auth(req))return send(res,401,{error:'Authentication required.'});
   if(pathname==='/api/admin/menu'&&req.method==='GET'){let items=await readItems();const q=clean(u.searchParams.get('q'),80).toLowerCase(),c=clean(u.searchParams.get('category'),80);if(q)items=items.filter(x=>[x.name,x.category,x.description].some(v=>v.toLowerCase().includes(q)));if(c)items=items.filter(x=>x.category===c);return send(res,200,items.map(pub))}
   if(pathname==='/api/admin/menu'&&(req.method==='POST')){try{const f=await formData(req),b=f.fields;const name=clean(b.name,100),category=clean(b.category,80),price=Number(b.price),stock=Math.max(0,Math.floor(Number(b.stockQty)||0));if(!name||!category||!priceOk(price))return send(res,400,{error:'Name, category and a valid price are required.'});const op=b.originalPrice===''?null:Number(b.originalPrice),dp=b.discountPrice===''?null:Number(b.discountPrice);if((op!==null&&!priceOk(op))||(dp!==null&&!priceOk(dp))||(op!==null&&dp!==null&&dp>op))return send(res,400,{error:'Please check original and discount prices.'});const image=await saveUpload(f.files.imageFile)||clean(b.image,1000);const item={id:'bt-'+crypto.randomUUID().slice(0,8),name,category,price,unit:clean(b.unit,60),stockQty:stock,description:clean(b.description,600),image,originalPrice:op,discountPrice:dp,featured:bool(b.featured),active:bool(b.active,true)};const items=await readItems();await writeItems([item,...items]);return send(res,201,pub(item))}catch(e){console.error(e);return send(res,400,{error:e.message||'Could not save the dish.'})}}
   const match=pathname.match(/^\/api\/admin\/menu\/([^/]+)$/);if(match&&req.method==='PUT'){try{const id=decodeURIComponent(match[1]),items=await readItems(),i=items.findIndex(x=>x.id===id);if(i<0)return send(res,404,{error:'Dish not found.'});const f=await formData(req),b=f.fields,price=Number(b.price),stock=Math.max(0,Math.floor(Number(b.stockQty)||0)),op=b.originalPrice===''?null:Number(b.originalPrice),dp=b.discountPrice===''?null:Number(b.discountPrice);if(!clean(b.name,100)||!clean(b.category,80)||!priceOk(price)||((op!==null&&!priceOk(op))||(dp!==null&&!priceOk(dp)))||(op!==null&&dp!==null&&dp>op))return send(res,400,{error:'Please check the required fields and prices.'});const image=await saveUpload(f.files.imageFile)||clean(b.image,1000)||items[i].image;items[i]={...items[i],name:clean(b.name,100),category:clean(b.category,80),price,unit:clean(b.unit,60),stockQty:stock,description:clean(b.description,600),image,originalPrice:op,discountPrice:dp,featured:bool(b.featured),active:bool(b.active)};await writeItems(items);return send(res,200,pub(items[i]))}catch(e){console.error(e);return send(res,400,{error:e.message||'Could not update the dish.'})}}
   if(match&&req.method==='DELETE'){try{const id=decodeURIComponent(match[1]),items=await readItems(),x=items.find(x=>x.id===id);if(!x)return send(res,404,{error:'Dish not found.'});await writeItems(items.filter(i=>i.id!==id));if(x.image?.startsWith('/uploads/'))fs.unlink(path.join(__dirname,'public',x.image)).catch(()=>{});return send(res,200,{ok:true})}catch(e){return send(res,500,{error:'Could not delete the dish.'})}}
 }
 return send(res,404,{error:'Not found.'});
}
async function serve(req,res){const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(u.pathname.startsWith('/api/'))return handleApi(req,res,u);let p=u.pathname==='/'?'/index.html':u.pathname;if(p==='/admin')p='/admin.html';const file=path.normalize(path.join(__dirname,'public',p));if(!file.startsWith(path.join(__dirname,'public')))return send(res,403,{error:'Forbidden'});try{const st=await fs.stat(file);if(st.isDirectory())return redirect(res,'/');res.writeHead(200,{'Content-Type':MIME[path.extname(file).toLowerCase()]||'application/octet-stream','Cache-Control':file.endsWith('.html')?'no-cache':'public, max-age=86400'});fsSync.createReadStream(file).pipe(res)}catch{if(!path.extname(p))return fs.readFile(path.join(__dirname,'public','index.html')).then(b=>{res.writeHead(200,{'Content-Type':MIME['.html']});res.end(b)}).catch(()=>send(res,404,{error:'Not found'}));send(res,404,{error:'Not found'})}}
await ensure();
http.createServer((req,res)=>serve(req,res).catch(e=>{console.error(e);send(res,500,{error:'Unexpected server error.'})})).listen(PORT,HOST,()=>console.log(`Bihari Thaath demo running on http://${HOST}:${PORT}`));
